<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use BezhanSalleh\FilamentShield\Facades\FilamentShield;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class ShieldSeeder extends Seeder
{
    public function run(): void
    {
        $guard = 'web';

        /*
        |--------------------------------------------------------------------------
        | Permission Actions (standar Filament Shield)
        |--------------------------------------------------------------------------
        */

        $actions = [
            'ViewAllData',
            'ViewAny',
            'View',
            'Create',
            'Update',
            'Delete',
            'Restore',
            'ForceDelete',
            'ForceDeleteAny',
            'RestoreAny',
            'Replicate',
            'Reorder',
        ];

        /*
        |--------------------------------------------------------------------------
        | Workflow Actions (custom, bukan dari Shield)
        |--------------------------------------------------------------------------
        */

        $workflowPermissions = [
            'Submit:LaporanInsiden',         // pelapor
            'Verifikasi:LaporanInsiden',      // kepala_unit: verifikasi (grading selesai) → diverifikasi
            'Kembalikan:LaporanInsiden',      // kepala_unit: kembalikan ke pelapor → revisi
            'Investigasi:LaporanInsiden',     // tim_mutu: mulai investigasi → investigasi
            'KembalikanUnit:LaporanInsiden',  // tim_mutu: kembalikan ke kepala_unit → revisi_unit
            'ForceEdit:LaporanInsiden',       // custom: force edit (override workflow locking)
        ];

        /*
        |--------------------------------------------------------------------------
        | Page Permissions (Shield HasPageShield)
        |--------------------------------------------------------------------------
        */

        $pagePermissions = [
            'View:PelaporanInsiden',  // akses halaman form pelaporan insiden
        ];

        /*
        |--------------------------------------------------------------------------
        | Resources
        |--------------------------------------------------------------------------
        */

        $resources = [
            'LaporanInsiden',
            'Role',
        ];

        /*
        |--------------------------------------------------------------------------
        | Generate Permissions
        |--------------------------------------------------------------------------
        */

        $permissions = collect($resources)
            ->flatMap(function ($resource) use ($actions) {
                return collect($actions)->map(fn($action) => "{$action}:{$resource}");
            });

        foreach ($permissions as $permission) {
            Permission::firstOrCreate([
                'name' => $permission,
                'guard_name' => $guard,
            ]);
        }

        foreach ($workflowPermissions as $permission) {
            Permission::firstOrCreate([
                'name' => $permission,
                'guard_name' => $guard,
            ]);
        }

        foreach ($pagePermissions as $permission) {
            Permission::firstOrCreate([
                'name' => $permission,
                'guard_name' => $guard,
            ]);
        }

        // Widget permissions (generated by Filament Shield)
        $widgetPermissions = collect(FilamentShield::getWidgets())
            ->flatMap(fn ($widget) => array_keys($widget['permissions'] ?? []))
            ->unique();

        foreach ($widgetPermissions as $permission) {
            Permission::firstOrCreate([
                'name' => $permission,
                'guard_name' => $guard,
            ]);
        }

        /*
        |--------------------------------------------------------------------------
        | Roles
        |--------------------------------------------------------------------------
        */

        $roles = [
            'super_admin',
            'admin',
            'tim_mutu',
            'kepala_unit',
            'pelapor',
            'manajemen',
        ];

        $roleInstances = [];

        foreach ($roles as $role) {
            $roleInstances[$role] = Role::firstOrCreate([
                'name' => $role,
                'guard_name' => $guard,
            ]);
        }

        /*
        |--------------------------------------------------------------------------
        | Assign Permissions
        |--------------------------------------------------------------------------
        */

        $allPermissions = Permission::all();

        // Super Admin → semua permission
        $roleInstances['super_admin']->syncPermissions($allPermissions);

        // Admin → semua laporan + manajemen role + semua workflow
        $adminPermissions = collect($actions)
            ->map(fn($action) => "{$action}:LaporanInsiden")
            ->merge([
                'ViewAny:Role',
                'View:Role',
                'Create:Role',
                'Update:Role',
                'Delete:Role',
                'Submit:LaporanInsiden',
                'Verifikasi:LaporanInsiden',
                'Kembalikan:LaporanInsiden',
                'Investigasi:LaporanInsiden',
                'KembalikanUnit:LaporanInsiden',
                'View:PelaporanInsiden',
                'ViewAllData:LaporanInsiden',
                'ForceEdit:LaporanInsiden',
            ]);

        $roleInstances['admin']->syncPermissions($adminPermissions);

        // Kepala unit → verifikasi & kembalikan ke pelapor
        $roleInstances['kepala_unit']->syncPermissions([
            'ViewAny:LaporanInsiden',
            'View:LaporanInsiden',
            'Update:LaporanInsiden',
            'Create:LaporanInsiden',
            'Investigasi:LaporanInsiden',
            'KembalikanUnit:LaporanInsiden',
            'Verifikasi:LaporanInsiden',
            'Kembalikan:LaporanInsiden',
            'Submit:LaporanInsiden',
            'View:PelaporanInsiden',

        ]);

        // Tim mutu → investigasi & kembalikan ke kepala unit
        $roleInstances['tim_mutu']->syncPermissions([
            'ViewAllData:LaporanInsiden',
            'ViewAny:LaporanInsiden',
            'View:LaporanInsiden',
            'Create:LaporanInsiden',
            'Investigasi:LaporanInsiden',
            'KembalikanUnit:LaporanInsiden',
            'Submit:LaporanInsiden',
            'View:PelaporanInsiden',
        ]);

        // Manajemen → hanya lihat
        $roleInstances['manajemen']->syncPermissions([
            'ViewAllData:LaporanInsiden',
            'ViewAny:LaporanInsiden',
            'View:LaporanInsiden',
        ]);

        // Pelapor → submit & lihat
        $roleInstances['pelapor']->syncPermissions([
            'View:LaporanInsiden',
            'ViewAny:LaporanInsiden',
            'Create:LaporanInsiden',
            'Update:LaporanInsiden',
            'Submit:LaporanInsiden',
            'View:PelaporanInsiden',

        ]);

        // Give widget access to roles that can view incidents
        foreach ($roleInstances as $role) {
            if ($role->hasPermissionTo('ViewAny:LaporanInsiden') || $role->hasPermissionTo('ViewAllData:LaporanInsiden')) {
                $role->givePermissionTo($widgetPermissions->toArray());
            }
        }
    }
}
